name: Docker Build and Push Image

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push amd64 image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: lvlinkeji/okmath:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
